image: node:lts

stages:
  - Publish Gastby

# These folders are cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

production:
  stage: Publish Gastby
  script:
    # Install via yarn with frozen-lockfile to allow reproducible dependencies and check-files option to check if the node_modules cache is valid.
    - yarn install --frozen-lockfile --check-files --non-interactive
    - ./node_modules/.bin/gatsby clean
    - ./node_modules/.bin/gatsby build --prefix-paths
  only:
    - main
  artifacts:
    paths:
      - public