name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: false

      - name: Remove all files into gh-pages branch
        run: |
          rm -rf *

      - uses: actions/checkout@v1

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.blog }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths